### ISSUE TITLE
Primesense (Xtion pro live) support? Dev tips?

### ISSUE THREAD

**Issue by sjobeek** [xxorde/librekinect#16]
I've got librekinect working with my Kinect, but I'd also love to use it with an Xtion pro live (primesense sensor) that I have sitting around. 

Do you have any advice or suggestions for getting this working?  I'm willing to experiment and hack around on the driver if I need to, though I'm quite a novice in this area. 

I was able to modify the USB device table in kinect.c and succeeded in getting /dev/video0 to appear, and camorama even managed to display "primesense camera" in it's titlebar, but unfortunately the video was unable to display and just recieved an error.

I just tweaked here the USB_DEVICE to match the Xtion pro live signiture from `lsusb`:
```
/* -- module initialisation -- */
static const struct usb_device_id device_table[] = {
        {USB_DEVICE(0x1d27, 0x0601)},
        {USB_DEVICE(0x045e, 0x02bf)},
        {}
};
```

Any tips or direction you could give me to get this working would be appreciated! I'm willing to develop and contribute this back as a PR if I can figure it out.

**Comment by TimboInSpace** [comment]
For the Xtion pro live, I've seen that many have success using OpenNI2. Maybe give that a go.

**Comment by sjobeek** [comment]
I did in fact have success with OpenNI2 drivers on the Rasperry Pi 2, which seemed to be fast enough for ~27 FPS at full VGA resolution.  

I definitely recommend that path for anyone else with an Xtion Pro Live.
