### ISSUE TITLE
Male load fails on raspbeery pi 2 B

### ISSUE THREAD

**Issue by nik012003** [xxorde/librekinect#25]
I am trying to run my xbox360 kinect on my raspberry pi 2. I have followed this guide ( https://github.com/xxorde/librekinect )without errors but at the last command ( make load ) gives me this error:
root@raspberrypi:/home/pi/librekinect-master# ls
gspca.c gspca.h kinect.c Makefile readme.md unload_drivers.sh
root@raspberrypi:/home/pi/librekinect-master# make load
make unload_drivers
make[1]: Entering directory '/home/pi/librekinect-master'
sudo sh unload_drivers.sh
Error: Module kinect is not currently loaded
Error: Module gspca is not currently loaded
Error: Module gspca_main is in use by: gspca_kinect
Error: Module gspca_kinect is in use
Error: Module * is not currently loaded
make[1]: Leaving directory '/home/pi/librekinect-master'
sudo modprobe videodev
sudo insmod gspca.ko
Error: could not load module gspca.ko: No such file or directory
Makefile:42: recipe for target 'load' failed
make: *** [load] Error 1
root@raspberrypi:/home/pi/librekinect-master#

I have downloaded 3.18.y rpi image

**Comment by DougieLawson** [comment]
I got this to build OK on my RPi 2B.
First thing was a bit of hacking the Makefile (because I didn't have the Linux source in /usr/src/linux)
and to update it for the problem reported in https://github.com/xxorde/librekinect/issues/15

Second thing was to update gspca.c for the bug reported in https://github.com/xxorde/librekinect/issues/14

build the code with ```make```

Third thing was to have the kinect powered up and connected before attempting ```make load```

My ../librekinect directory has the following files after the ```make``` is complete
```
gspca.c      gspca.mod.o  kinect.mod.c  modules.order
gspca.h      gspca.o      kinect.mod.o  Module.symvers
gspca.ko     kinect.c     kinect.o      readme.md
gspca.mod.c  kinect.ko    Makefile      unload_drivers.sh
```

You appear to have missed the make step.

**Comment by nik012003** [comment]
pi@raspberrypi ~/librekinect $ ls
gspca.c      gspca.mod.o  kinect.mod.c  modules.order
gspca.h      gspca.o      kinect.mod.o  Module.symvers
gspca.ko     kinect.c     kinect.o      readme.md
gspca.mod.c  kinect.ko    Makefile      unload_drivers.sh
pi@raspberrypi ~/librekinect $ make load
make unload_drivers
make[1]: Entering directory '/home/pi/librekinect'
sudo sh unload_drivers.sh
Error: Module kinect is not currently loaded
Error: Module gspca is not currently loaded
Error: Module gspca_main is in use by: gspca_kinect
Error: Module gspca_kinect is in use
Error: Module gspca is not currently loaded
Error: Module kinect is not currently loaded
make[1]: Leaving directory '/home/pi/librekinect'
sudo modprobe videodev
sudo insmod gspca.ko
Error: could not insert module gspca.ko: Invalid module format
Makefile:42: recipe for target 'load' failed
make: *** [load] Error 1
pi@raspberrypi ~/librekinect $



Now i have this error

**Comment by DougieLawson** [comment]
Try 
```file gspca.ko```
You should get something like
```
pi@eagle:/tmp/librekinect$ file gspca.ko
gspca.ko: ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), BuildID[sha1]  =a5a67851e257dc6318bf549a1b28cbd3981e3a29, not stripped
pi@eagle:/tmp/librekinect$
``` 
the id string will be different on your system. If it doesn't show ```ARM, EABI5``` try rebuilding it with
 
```make clean && make && make load```

**Comment by nik012003** [comment]
@raspberrypi ~ $ cd librekinect
pi@raspberrypi ~/librekinect $ file gspca.ko
gspca.ko: ELF 32-bit LSB relocatable, ARM, version 1 (SYSV), BuildID[sha1]=0xdf3d85531a77c77023baa5d78906ba62dfc7bb7a, not stripped
pi@raspberrypi ~/librekinect $ make clean && make && make load
rm -f *~ *.o *.ko
rm -f .built_in.o.cmd built_in.o
rm -f .*.cmd *.ko *.mod.c
rm -f *.symvers *.order
rm -rf .tmp_versions
rm -f *.log
rm -rf modules.order *.mod.c
rm -rf Module.symvers
make pc
make[1]: Entering directory '/home/pi/librekinect'
make -C /lib/modules/3.18.11-v7/build M=/home/pi/librekinect modules
make[2]: Entering directory '/usr/src/linux'
  CC [M]  /home/pi/librekinect/gspca.o
  CC [M]  /home/pi/librekinect/kinect.o
  Building modules, stage 2.
  MODPOST 2 modules
  CC      /home/pi/librekinect/gspca.mod.o
  LD [M]  /home/pi/librekinect/gspca.ko
  CC      /home/pi/librekinect/kinect.mod.o
  LD [M]  /home/pi/librekinect/kinect.ko
make[2]: Leaving directory '/usr/src/linux'
make[1]: Leaving directory '/home/pi/librekinect'
make unload_drivers
make[1]: Entering directory '/home/pi/librekinect'
sudo sh unload_drivers.sh
Error: Module kinect is not currently loaded
Error: Module gspca is not currently loaded
Error: Module gspca_main is in use by: gspca_kinect
Error: Module gspca_kinect is in use
Error: Module gspca is not currently loaded
Error: Module kinect is not currently loaded
make[1]: Leaving directory '/home/pi/librekinect'
sudo modprobe videodev
sudo insmod gspca.ko
Error: could not insert module gspca.ko: Invalid module format
Makefile:42: recipe for target 'load' failed
make: *** [load] Error 1
pi@raspberrypi ~/librekinect $ file gspca.ko
gspca.ko: ELF 32-bit LSB relocatable, ARM, version 1 (SYSV), BuildID[sha1]=0xdf3d85531a77c77023baa5d78906ba62dfc7bb7a, not stripped
pi@raspberrypi ~/librekinect $ file gspca.ko



Dame error :/

**Comment by nik012003** [comment]
*same

**Comment by nik012003** [comment]
If someone has already compiled for librekinect Rpi2 with 3.18.11-v7, can send me his folder librekinect ? Thanks
P.S. My email is guerrera.nicola@gmail.com

**Comment by robertheinze** [comment]
@nik012003 Have just brought it up! I will send it to you ... But follow https://github.com/xxorde/librekinect/issues/15 @sjobeek solution helps. Even the error 38 on make load does not matter

**Comment by nik012003** [comment]
THX robertheinze !But i have the dame error :(

**Comment by robertheinze** [comment]
no problem, it still works on camorama in my case

**Comment by nik012003** [comment]
I reinstalled raspbian , but I always get the same error .Its now I have the version 3.18.7-v7+

**Comment by YadavKapil** [comment]
Hi,

Make_load is not working because of missing gspca.ko file. So, may be, make command is not working properly (thats why gspca.ko is not present ). But I dont know the way to fix this problem. 

Here are the outputs - 

**make**
```
pi@raspberrypi ~/librekinect $ sudo make
make pc
make[1]: Entering directory '/home/pi/librekinect'
make -C /lib/modules/3.18.11-v7/build M= modules
make[2]: Entering directory '/usr/src/linux'
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[3]: 'include/generated/mach-types.h' is up to date.
  CALL    scripts/checksyscalls.sh
  Building modules, stage 2.
  MODPOST 1361 modules
make[2]: Leaving directory '/usr/src/linux'
make[1]: Leaving directory '/home/pi/librekinect'
```
**make load**
```
pi@raspberrypi ~/librekinect $ sudo make load
make unload_drivers
make[1]: Entering directory '/home/pi/librekinect'
sudo sh unload_drivers.sh
tried to unload all related drivers (and possibly more ;)
make[1]: Leaving directory '/home/pi/librekinect'
sudo modprobe videodev
sudo insmod gspca.ko
Error: could not load module gspca.ko: No such file or directory
Makefile:42: recipe for target 'load' failed
make: *** [load] Error 1
```
**file system after make load**
```
pi@raspberrypi ~/librekinect $ ls
gspca.c  gspca.h  kinect.c  Makefile  readme.md  unload_drivers.sh
pi@raspberrypi ~/librekinect $ 
```

**Comment by YadavKapil** [comment]
I guess the problem is in your kernel compatibilty. Since you have raspbian 3.18.7, did you use 3.18 tar file in this line `wget https://github.com/raspberrypi/linux/archive/rpi-3.12.y.tar.gz` ?

**Comment by YadavKapil** [comment]
Hi @robertheinze . I have installed this library but I am getting rgb stream instead of depth stream as in #27 . Can you tell me how did you get depth stream ? Thanks

**Comment by nik012003** [comment]
I have used wget https://github.com/raspberrypi/linux/archive/rpi-3.18.y.tar.gz not 3.12

**Comment by robertheinze** [comment]
@YadavKapil Sorry, I am getting RGB stream as well.

**Comment by nik012003** [comment]
I Followed All steps , adjusted the Makefile and gspca , recompiled the kernel but I ALWAYS THE SAME ERROR !

**Comment by nik012003** [comment]
now it works !

**Comment by YadavKapil** [comment]
@nik012003 its good that it works now. btw, can u post your depth image that you got so that I can compare it with mine?... i think.. I am not getting a proper depth image as in #28. I have posted mine in issue #28
