### ISSUE TITLE
depth image - still dropping packets ???

### ISSUE THREAD

**Issue by YadavKapil** [xxorde/librekinect#28]
Hi,

Can anyone please post his/her own depth image for comparision with my depth image?

My depth image is similar to the one I got from libfreenect (libfreenect was working but with dropped packets). Thats why, I think the packets are still being dropped inspite of using librekinect in my case. 
I might be doing something wrong. Can you please tell me whats wrong?

My depth image from librekinect -
![screenshot from 2015-04-26 00 54 51](https://cloud.githubusercontent.com/assets/3341076/7334579/6ec16772-ebb5-11e4-87d8-a358c8effe76.png)

My depth image from libfreenect - 
![screenshot from 2015-04-26 00 52 25](https://cloud.githubusercontent.com/assets/3341076/7334578/5ea04660-ebb5-11e4-8d46-4fb6a7f747d7.png)

What could be the reason for this?
@robertheinze @lucyking @sjobeek Can you please help me by posting your own depth image for comparision with my depth image?

Thanks

**Comment by nik012003** [comment]
http://imgur.com/V0RZTD2


Sorry for the photo taken by the phone

**Comment by YadavKapil** [comment]
Thanks for the image... I really helped me.. I guess there is something wrong in my setup.

One more question.... are you getting grayscale depth image or a coloured depth image(as in my case) ?

**Comment by nik012003** [comment]
I'm getting grayscale depth image only.

**Comment by robertheinze** [comment]
Mine looks exactly the same way

**Comment by lucyking** [comment]
the same as above:
![pic](http://img5.douban.com/view/photo/large/public/p2206961857.jpg)

**Comment by lucyking** [comment]
I also only got grayscale img.
I doubt the problem is that you using Remmina Remote Desktop Clinet.
If you connect the Raspberry Pi directly to a monitor,everything may goes well ;-)

**Comment by YadavKapil** [comment]
@lucyking Thanks for the suggestion... Remmina was indeed the problem... I changed its setting to True color (32bpp) and quality slowest (best). And i started getting proper grayscale images.
