### ISSUE TITLE
IR Stream Displayed instead of Depth Stream

### ISSUE THREAD

**Issue by TOTON95** [xxorde/librekinect#48]
Finally got to make work librekinect on a **Raspberry Pi 3** and suddenly the next time I open de stream I got a `IR stream` instead of a `Depth Stream`, I don't have idea about why few times i got the depth stream as expected and then got this Stream. Attaching photos...

First:
![2017-01-06-023018_742x790_scrot](https://cloud.githubusercontent.com/assets/18298985/21713378/55563be8-d3bf-11e6-87f9-4b7e936141d2.png)

Finally:
![2017-01-06-031939_742x798_scrot 1](https://cloud.githubusercontent.com/assets/18298985/21713682/bbabb462-d3c0-11e6-899b-bedb32efdc9d.png)

Sometimes doesn't open :(

**Comment by lucyking** [comment]
- I also met this problem on Raspberry Pi 2. Here's the screenshot ![screenshot](https://img1.doubanio.com/view/photo/photo/public/p2206961887.jpg)

- May you can try my [pickinect code](https://github.com/lucyking/pickinect) to read Kinect directly without video player. I'v just run these code on Pi2(poor hardware,not very well) and x86 PC(ubuntu 14.10, very well). Because Pi3 's hardware is powerful may it can run as well as x86.

**Comment by TOTON95** [comment]
@lucyking Sorry for the delay, Oh okok I see. So this is a common  issue currently than I thought. I will give it a try today with your library, and I hope it  works and if it does I will share the Performance Statics.

**Comment by yehonathanlitman** [comment]
Hello, Just wondering, were you eventually able to fix the issues? If so, how? I'm looking to run the Kinect 360 with my Raspberry Pi 3 soon but haven't started yet.

**Comment by TOTON95** [comment]
Hello @indigomega, unfortunately my sd got corrupted and I have not continued the usage of this resource when I re-installed everything, if I can remember I used to unload the resource and load it again (I'm not so sure if that was all):

`make unload
make load`

or just load it:

`make load`

You could make a script too, it's a little tricky sometimes. Another way I usually did was to reboot the raspberry pi (make sure to unplug the kinect first, to avoid electrical issues).

_I recommend you to give a shot to the new instructions of the +3.17 kernel that **xxorde** published in his readme file._

I will try that option on a free weekend if you would like to join.

**Comment by lucyking** [comment]
Agree with @TOTON95, I use ```sudo make unload ; sudo  make load``` serveral times until make Kinect 
depth module works well on RPI2. Read the [load-librekinect section](https://github.com/lucyking/pickinect/blob/master/README.md#load-librekinect) for more details.

**Comment by TOTON95** [comment]
Closing since no more activity is shown.
